### ISSUE TITLE
Context menu doesn't work with Jubler on Windows

### ISSUE THREAD

**Issue by andalou** [teras/Jubler#10]
When I right click on a .srt file and choose 'Open with' Jubler, it
doesn't open Jubler at all.
It also doesn't start if I run C:\Program Files\Jubler\Jubler.exe from
the command line.
It only works if I run java -jar C:\Program Files\Jubler\lib\jubler.jar

I'm using Window 7 64bit, java 1.8.0_221, and Jubler 6.0.2

The ouptut from 'java -jar jubler.jar' is:

Unable to locate language en
Registering plugin Multi-platform application support
Registering plugin ASpell checker
Registering plugin Auto update
Registering plugin Text subtitles
Registering plugin Basic tools
Registering plugin MPlayer media player
Registering plugin Zemberek spell checker
7 plugins found
33 plugin items found
5 listeners found
Unable to locate library ffdecode
Found defined encoding UTF-8
Found file PreSegmented Text
White spaces are required between publicId and systemId.

**Comment by teras** [comment]
Thank you for the thorow report.
I'll have a look at it

**Comment by carlitossuper1** [comment]
Adding to this issue:

If I double clic on a .srt file, the Jubler splash screen appears briefly and then nothing happens. Also, manually opening Jubler from start menu and then double click on a .srt file still does nothing. I have to use File > Open or drag the subtitle.

**Comment by teras** [comment]
I confirm that on my system I have the same behavior. I have found that this is a problem with [Launch4J](http://launch4j.sourceforge.net) . I even tried to rollback to previous versions but none of them worked reliable any more. If, instead of linking to the jubler executable, link to the javaw.exe directly, the problem disappears (but then we loose the nice application icon).

The forum there seems dead and nobody answers the problems. I am afraid the only thing I could do is to disable the file association under windows -- this is not an optimal solution but at least it would be consistent.


Of course any more ideas are more than welcome.

**Comment by teras** [comment]
One more note: on their documentation clearly states:

> Command line arguments cannot be passed to the executable

I think this used to work in the past, maybe something broke in the meantime

**Comment by teras** [comment]
Please have a look at the latest version -- I tried my own windows launcher, hope it works :) 
https://github.com/teras/Jubler/releases/tag/v7.0.0-beta1

**Comment by carlitossuper1** [comment]
Works for me, too. Thanks!
